site_name: ParkEase
site_description: AI & Cloud-based Parking Management by SLTMobitel
site_author: SLTMobitel Innovation Center – The Embryo

repo_url: https://github.com/YourUsername/YourRepo
repo_name: GitHub 

theme:
  name: material
  logo: images/parkease-logo.png
  favicon: images/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
        
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.top
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - navigation.footer
    - search.suggest
    - search.highlight

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/@mdi/js@7.2.96/mdi.min.js

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Introduction:
      - Overview: overview.md
      - Getting Started: getting-started.md
  - Guides:
      - Deployment: deployment.md
      - Integration: integration.md
      - Security: security.md
  - Management:
      - Console:
          - Dashboard: console/dashboard.md
          - Parking Map: console/parking-map.md
          - Billing: console/billing.md
  - Help:
      - Troubleshooting: troubleshooting.md
      - Support: support.md


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/YourUsername/YourRepo
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/yourprofile

copyright: >
  © 2025 SLTMobitel Innovation Center – The Embryo.  <br>
  Made by Isuru M Dasanayake using MkDocs Material.
