site_name: ParkEase
site_description: AI & Cloud-based Parking Management by SLTMobitel
site_author: SLTMobitel Innovation Center – The Embryo

theme:
  name: material
  logo: images/parkease-logo.png
  favicon: images/favicon.ico

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
        
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.top
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - search.suggest
    - search.highlight

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/@mdi/js@7.2.96/mdi.min.js

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Overview: overview.md
  - Getting Started: getting-started.md
  - Console:
      - Dashboard: console/dashboard.md
      - Parking Map: console/parking-map.md
      - Billing: console/billing.md
  - Security: security.md
  - Integration: integration.md
  - Deployment: deployment.md
  - Troubleshooting: troubleshooting.md
  - About: about.md
  - Support: support.md
